image: maven:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - quality

cache:
  paths:
    - .m2/repository
  key: "$CI_JOB_NAME"

compile_job:
  stage: build
  script:
    - mvn compile
