image: maven:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - quality

cache:
  paths:
    - .m2/repository
  key: "$CI_JOB_NAME"

compile_job:
  stage: build
  script:
    - mvn compile

test_job:
  stage: test
  script:
    - mvn test

quality_job:
  stage: quality
  script:
    - mvn verify